NoticiasMVC/Models/Clasificaciones.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace NoticiasMVC.Models
{
    public class Clasificaciones
    {
        [Key]
        public int IdClasificacion { get; set; }

        [Required]
        [DisplayName("Clasificación")]
        public string NombreClasificacion { get; set; }

        [Required]
        [DisplayName("Descripción")]
        public string DescripcionClasificacion { get; set; }
    }
}

NoticiasMVC/Controllers/ClasificacionesController.cs
using Microsoft.AspNetCore.Mvc;
using NoticiasMVC.Data;
using NoticiasMVC.Models;
using static System.Net.Mime.MediaTypeNames;

namespace NoticiasMVC.Controllers
{
    public class ClasificacionesController : Controller
    {
        //agregamos un objeto de nuestra clase AppDbContext
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        //inicializamos nuestro objeto de AppDbContext
        public ClasificacionesController
        (
            AppDbContext context, IWebHostEnvironment webHostEnvironment
        )
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        //ruta -> Views/Clasificaciones/Index
        public IActionResult Index()
        {
            //este objeto contine las Clasificaciones
            IEnumerable<Clasificaciones> ListaClasificaciones = _context.Clasificaciones;
            //pasamos el objeto ListaClasificacion a la vista
            return View(ListaClasificaciones);
        }

        //Metodo HttpGet
        //ruta -> Views/Clasificaciones/Create
        public IActionResult Create() {
            return View();
        }


        //Metodo HttpPost
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Clasificaciones AddClasificacion) { 
            //verficamos que los datos se enviaron correctamente
            if (ModelState.IsValid)
            {
                //guardando
                _context.Clasificaciones.Add(AddClasificacion);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(AddClasificacion);
        }

        //Metodo HttpGet
        //ruta -> Views/Clasificaciones/Edit/{IdClasificacion}
        public IActionResult Edit(int? Id)
        {
            //verficamos que se paso el id por la url
            if (Id == null || Id == 0) {
                return NotFound();
            }

            //Consultamos el registro segun su ID
            var Clasificacion = _context.Clasificaciones.Find(Id);

            //si no encuentra el registro
            if (Clasificacion == null) {
                return NotFound();
            }
            //Si el registro es encotrado pasamos el objeto a la vista
            return View(Clasificacion);
        }

        //Metodo HttpPost
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Clasificaciones EditClasificacion)
        {
            //verficamos que los datos se enviaron correctamente
            if (ModelState.IsValid)
            {
                //guardando
                _context.Clasificaciones.Update(EditClasificacion);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(EditClasificacion);
        }

        //Metodo HttpGet
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var Clasificacion = _context.Clasificaciones.Find(Id);

            if (Clasificacion == null)
            {
                return NotFound();
            }
           
            _context.Clasificaciones.Remove(Clasificacion);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

NoticiasMVC/Views/Clasificaciones/Create.cshtml
@model NoticiasMVC.Models.Clasificaciones

@{
    ViewData["Title"] = "Crear Clasificaciones";
}

<div class="row">
    <div class="col-12">
        <h4>@ViewData["Title"]</h4>
    </div>

    <form asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-edit"></i> Registro de Clasificaciones
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6 col-sm-12">
                            <label class="form-label" asp-for="NombreClasificacion"></label>
                            <input asp-for="NombreClasificacion" class="form-control"
                            placeholder="Ingresa el nombre de la Clasificacion"/>
                            <span class="text-danger" asp-validation-for="NombreClasificacion"></span>
                        </div>

                        <div class="col-12">
                            <label class="form-label" asp-for="DescripcionClasificacion"></label>
                            <textarea asp-for="DescripcionClasificacion" class="form-control" id="descripcion" rows="5"></textarea>
                            <span class="text-danger" asp-validation-for="DescripcionClasificacion"></span>
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-edit"></i> Agregar
                    </button>

                    <a class="btn btn-danger" type="button" asp-action="Index">
                        <i class="fa fa-rotate-back"></i> Cancelar
                    </a>
                </div> 
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>
        tinymce.init({
            selector: '#descripcion',
            plugins: [
                'a11ychecker', 'advlist', 'advcode', 'advtable', 'autolink', 'checklist', 'export',
                'lists', 'link', 'image', 'charmap', 'preview', 'anchor', 'searchreplace', 'visualblocks',
                'powerpaste', 'fullscreen', 'formatpainter', 'insertdatetime', 'media', 'table', 'help', 'wordcount'
            ],
            toolbar: 'undo redo | formatpainter casechange blocks | bold italic backcolor | ' +
                'alignleft aligncenter alignright alignjustify | ' +
                'bullist numlist checklist outdent indent | removeformat | a11ycheck code table help'
        });
    </script>
}

NoticiasMVC/Views/Clasificaciones/Edit.cshtml
@model NoticiasMVC.Models.Clasificaciones

@{
    ViewData["Title"] = "Editar Clasificaciones";
}

<div class="row">
    <div class="col-12">
        <h4>@ViewData["Title"]</h4>
    </div>

    <form asp-action="Edit" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="IdClasificacion" hidden />
        
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-edit"></i> Editar de Clasificaciones
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6 col-sm-12">
                            <label class="form-label" asp-for="NombreClasificacion"></label>
                            <input asp-for="NombreClasificacion" class="form-control"
                                   placeholder="Ingresa el nombre de la Clasificacion" />
                            <span class="text-danger" asp-validation-for="NombreClasificacion"></span>
                        </div>


                        <div class="col-lg-12 col-sm-12">
                            <label class="form-label" asp-for="DescripcionClasificacion"></label>
                            <textarea asp-for="DescripcionClasificacion" class="form-control" id="descripcion" rows="5"></textarea>
                            <span class="text-danger" asp-validation-for="NombreClasificacion"></span>
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-edit"></i> Actualizar
                    </button>

                    <a class="btn btn-danger" type="button" asp-action="Index">
                        <i class="fa fa-rotate-back"></i> Cancelar
                    </a>
                </div>
            </div>
        </div>

    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    <script>
        function validateInput() {
            if (document.getElementById("uploadBox").value == "") {
                Swal.fire(
                    'Error',
                    'Se debe de adjuntar una imagen',
                    'error'
                )
            }
        }
    </script>

    <script>
        tinymce.init({
            selector: '#descripcion',
            plugins: [
                'a11ychecker', 'advlist', 'advcode', 'advtable', 'autolink', 'checklist', 'export',
                'lists', 'link', 'image', 'charmap', 'preview', 'anchor', 'searchreplace', 'visualblocks',
                'powerpaste', 'fullscreen', 'formatpainter', 'insertdatetime', 'media', 'table', 'help', 'wordcount'
            ],
            toolbar: 'undo redo | formatpainter casechange blocks | bold italic backcolor | ' +
                'alignleft aligncenter alignright alignjustify | ' +
                'bullist numlist checklist outdent indent | removeformat | a11ycheck code table help'
        });
    </script>
}

NoticiasMVC/Views/Clasificaciones/Index.cshtml
@model IEnumerable<NoticiasMVC.Models.Clasificaciones>

@{
    ViewData["Title"] = "Lista de Clasificaciones";
}

<div class="row">
    <div class="col-12 mt-3">
        <h4>
            @ViewData["Title"]
            <a class="btn btn-primary" asp-controller="Clasificaciones" asp-action="Create">
                <i class="fa fa-pen"></i> Agregar
            </a>
        </h4>
    </div>

    <!--card categorias-->
    <div class="col-12">
        <div class="card shadow-sm">
            <div class="card-header text-primary">
                <i class="fa-solid fa-database"></i> Lista de Registros
            </div>

            <div class="card-body">
                @if (Model.Count() > 0)
                {
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <tr>
                                <th>Id</th>
                                <th>Nombre</th>
                                <th>Descripción</th>
                                <th colspan="2">Opciones</th>
                            </tr>
                            @foreach (var clasificacion in Model)
                            {
                                <tr>
                                    <td>@clasificacion.IdClasificacion</td>
                                    <td>@clasificacion.NombreClasificacion</td>
                                    <td>@Html.Raw(clasificacion.DescripcionClasificacion)</td>
                                    <td>
                                        <a class="btn btn-primary" asp-controller="Clasificaciones"
                                   asp-action="Edit" asp-route-Id="@clasificacion.IdClasificacion">
                                            <i class="fa fa-edit"></i> Editar
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-danger" onclick="deleteClasificacion(@clasificacion.IdClasificacion);">
                                            <i class="fa fa-trash"></i> Eliminar
                                        </a>
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                }
                else
                {
                    <div class="alert alert-primary">
                        No existen registros actuales de Clasificaciones
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>
        const deleteClasificacion = (Id) => {
            Swal.fire({
                title: 'Quieres borrar esta clasificación?',
                text: "Una vez borrada no podras recurperarla",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si, eliminar!'
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire(
                        'Eliminado!',
                        'Tu registro fue eliminado correctamente.',
                        'success'
                    )
                    //espera para recargar la pagina
                    setTimeout(() => {
                        location.href = "/Categorias/Delete/" + Id
                    }, 500);
                }
            })
        }
    </script>
}