NoticiasMVC/Models/Noticias.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace NoticiasMVC.Models
{
    public class Noticias
    {
        [Key]
        public int IdNoticia { get; set; }

        [Required]
        [DisplayName("Titulo")]
        public string TituloNoticia { get; set;}

        [Required]
        [DisplayName("Descripción de la Noticia")]
        public string DescripcionNoticia { get; set; }

        [DisplayName("Imagen")]
        public string? ImagenNoticia { get; set; }

        [DisplayName("Categoría")]
        public int IdCategoria { get; set; }

        //agregando relaciones entre tablas noticias -> categorias
        [ForeignKey("IdCategoria")]
        public virtual Categorias? Categoria { get; set; }

        [DisplayName("Clasificación")]
        public int IdClasificacion { get; set; }

        //agregando relaciones entre tablas noticias -> clasificaciones
        [ForeignKey("IdClasificacion")]
        public virtual Clasificaciones? Clasificacion { get; set; }

        public DateTime? FechaIngreso { get; set; }

        public DateTime? FechaActualizacion { get; set; }
    }
}

NoticiasMVC/ViewModels/NoticiasView.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using NoticiasMVC.Models;

namespace NoticiasMVC.ViewModels
{
    public class NoticiasView
    {
        //referencia al modelo noticias
        public Noticias? Noticias { get; set; }

        //Propiedades para lsita de seleccion de categorias y clasificaciones
        public IEnumerable<SelectListItem>? CategoriasSelectList { get; set; }
        public IEnumerable<SelectListItem>? ClasificacionesSelectList { get; set; }
    }
}

NoticiasMVC/Controllers/NoticiasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NoticiasMVC.Data;
using NoticiasMVC.Models;
using NoticiasMVC.ViewModels;

namespace NoticiasMVC.Controllers
{
    public class NoticiasController : Controller
    {
        //agregamos un objeto de nuestra clase AppDbContext
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        //inicializamos nuestro objeto de AppDbContext
        public NoticiasController
        (
            AppDbContext context, IWebHostEnvironment webHostEnvironment
        )
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        //ruta -> Views/Noticias/Index
        public IActionResult Index()
        {
            //este objeto contine las Noticias
            IEnumerable<Noticias> ListaNoticias = _context.Noticias;

            foreach (var noticia in ListaNoticias)
            {
                noticia.Categoria = _context.Categorias.FirstOrDefault(
                    cat => cat.IdCategoria == noticia.IdCategoria
                );
                noticia.Clasificacion = _context.Clasificaciones.FirstOrDefault(
                    cla => cla.IdClasificacion == noticia.IdClasificacion
                );
            }
            //pasamos el objeto ListaNoticia a la vista
            return View(ListaNoticias);
        }

        //Metodo HttpGet
        //ruta -> Views/Noticias/Create
        public IActionResult Create() {

            NoticiasView Noticia = new NoticiasView()
            {
                Noticias = new Noticias(),
                CategoriasSelectList = _context.Categorias.Select(
                    i => new SelectListItem {
                        Text = i.NombreCategoria,
                        Value = i.IdCategoria.ToString()
                    }
                ),
                ClasificacionesSelectList = _context.Clasificaciones.Select(
                    i => new SelectListItem
                    {
                        Text = i.NombreClasificacion,
                        Value = i.IdClasificacion.ToString()
                    }
                )
            };
            
            return View(Noticia);
        }

        //metodo para subir imagenes al servidor
        private string SaveImageServer(bool IsUpdate, string Imagen) {
            //objetos para el manejo de archivos
            var ImageFile = HttpContext.Request.Form.Files;
            var WebRootPath = _webHostEnvironment.WebRootPath;
            string Upload = WebRootPath + WebConst.NoticiasPath; //Nueva ubicación del archivo

            if (IsUpdate)
            {
                if (ImageFile.Count > 0)
                {
                    var OldFile = Path.Combine(Upload, Imagen);
                    if (System.IO.File.Exists(OldFile))
                    {
                        System.IO.File.Delete(OldFile);
                    }
                }
                else
                {
                    return Imagen;
                }
            }
            string ImageFileName = Guid.NewGuid().ToString(); //Generando un nuevo nombre para la imagen
            string Extension = Path.GetExtension(ImageFile[0].FileName);//Obteniendo extension de archivo
            //Guardando archivo en el servidor
            using var ImageFileStream = new FileStream(
                Path.Combine(Upload, ImageFileName + Extension),
                FileMode.Create
            );
            ImageFile[0].CopyTo(ImageFileStream);
            return ImageFileName + Extension;
        }

        //Metodo HttpPost
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(NoticiasView AddNoticia) { 
            //verficamos que los datos se enviaron correctamente
            if (ModelState.IsValid)
            {
                string SaveImage = SaveImageServer(
                    false, AddNoticia.Noticias.ImagenNoticia
                );
                //actualzamos el nombre de la imagen en el modelo
                AddNoticia.Noticias.ImagenNoticia = SaveImage;
                AddNoticia.Noticias.FechaIngreso = DateTime.Now;
                AddNoticia.Noticias.FechaActualizacion = DateTime.Now;
                //guardando
                _context.Noticias.Add(AddNoticia.Noticias);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            AddNoticia.CategoriasSelectList = _context.Categorias.Select(
                i => new SelectListItem
                {
                    Text = i.NombreCategoria,
                    Value = i.IdCategoria.ToString()
                }
            );

            AddNoticia.ClasificacionesSelectList = _context.Clasificaciones.Select(
                i => new SelectListItem
                {
                    Text = i.NombreClasificacion,
                    Value = i.IdClasificacion.ToString()
                }
            );

            return View(AddNoticia);
        }

        //Metodo HttpGet
        //ruta -> Views/Noticias/Edit/{IdNoticia}
        public IActionResult Edit(int? Id)
        {
            //verficamos que se paso el id por la url
            if (Id == null || Id == 0) {
                return NotFound();
            }

            //Consultamos el registro segun su ID
            NoticiasView Noticia = new NoticiasView()
            {
                Noticias = _context.Noticias.Find(Id),
                CategoriasSelectList = _context.Categorias.Select(
                    i => new SelectListItem{
                            Text = i.NombreCategoria,
                            Value = i.IdCategoria.ToString()
                        }
                    ),
                ClasificacionesSelectList = _context.Clasificaciones.Select(
                    i => new SelectListItem
                    {
                        Text = i.NombreClasificacion,
                        Value = i.IdClasificacion.ToString()
                    }
                )
            };
            //si no encuentra el registro
            if (Noticia == null) {
                return NotFound();
            }
            //Si el registro es encotrado pasamos el objeto a la vista
            return View(Noticia);
        }

        //Metodo HttpPost
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(NoticiasView EditNoticia)
        {
            //verficamos que los datos se enviaron correctamente
            if (ModelState.IsValid)
            {
                string SaveImage = SaveImageServer(true, EditNoticia.Noticias.ImagenNoticia);
                //actualzamos el nombre de la imagen en el modelo
                EditNoticia.Noticias.ImagenNoticia = SaveImage;
                EditNoticia.Noticias.FechaActualizacion = DateTime.Now;
                //guardando
                _context.Noticias.Update(EditNoticia.Noticias);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            EditNoticia.CategoriasSelectList = _context.Categorias.Select(
                i => new SelectListItem
                {
                    Text = i.NombreCategoria,
                    Value = i.IdCategoria.ToString()
                }
            );

            EditNoticia.ClasificacionesSelectList = _context.Clasificaciones.Select(
                i => new SelectListItem
                {
                    Text = i.NombreClasificacion,
                    Value = i.IdClasificacion.ToString()
                }
            );
            return View(EditNoticia);
        }

        //Metodo HttpGet
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
            {
                return NotFound();
            }

            var Noticia = _context.Noticias.Find(Id);

            if (Noticia == null)
            {
                return NotFound();
            }
           
            string Upload = _webHostEnvironment.WebRootPath + WebConst.NoticiasPath;
            var OldFile = Path.Combine(Upload, Noticia.ImagenNoticia);
            
            if (System.IO.File.Exists(OldFile))
            {
                System.IO.File.Delete(OldFile);
            }

            _context.Noticias.Remove(Noticia);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

NoticiasMVC/Views/Noticias/Create.cshtml
@model NoticiasMVC.ViewModels.NoticiasView

@{
    ViewData["Title"] = "Crear Noticias";
}

<div class="row">
    <div class="col-12">
        <h4>@ViewData["Title"]</h4>
    </div>

    <form asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-edit"></i> Registro de Noticias
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6 col-sm-12 mb-3">
                            <label class="form-label" asp-for="Noticias.TituloNoticia"></label>
                            <input asp-for="Noticias.TituloNoticia" class="form-control"
                                   placeholder="Ingresa el nombre de la categoria" />
                            <span class="text-danger" asp-validation-for="Noticias.TituloNoticia"></span>
                        </div>

                        <div class="col-lg-6 col-sm-12 mb-3">
                            <label class="form-label" asp-for="Noticias.ImagenNoticia"></label>
                            <input type="file" name="files" id="uploadBox" class="form-control" />
                        </div>

                        <div class="col-lg-6 col-sm-12 mb-3">
                            <label class="form-label" asp-for="Noticias.IdCategoria"></label>
                            <select asp-for="Noticias.IdCategoria" class="form-control" asp-items="@Model.CategoriasSelectList">
                                <option disabled selected>Seleccionar Categoría</option>
                            </select>
                            <span class="text-danger" asp-validation-for="Noticias.IdCategoria"></span>
                        </div>

                        <div class="col-lg-6 col-sm-12 mb-3">
                            <label class="form-label" asp-for="Noticias.IdClasificacion"></label>
                            <select asp-for="Noticias.IdClasificacion" class="form-control" asp-items="@Model.ClasificacionesSelectList">
                                <option disabled selected>Seleccionar Clasificación</option>
                            </select>
                            <span class="text-danger" asp-validation-for="Noticias.IdClasificacion"></span>
                        </div>

                        <div class="col-12">
                            <label class="form-label" asp-for="Noticias.DescripcionNoticia"></label>
                            <textarea asp-for="Noticias.DescripcionNoticia" class="form-control" id="descripcion" rows="5"></textarea>
                            <span class="text-danger" asp-validation-for="Noticias.DescripcionNoticia"></span>
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <button class="btn btn-primary" type="submit" onclick="return validateInput()">
                        <i class="fa fa-edit"></i> Agregar
                    </button>

                    <a class="btn btn-danger" type="button" asp-action="Index">
                        <i class="fa fa-rotate-back"></i> Cancelar
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    <script>
        function validateInput() {
            if (document.getElementById("uploadBox").value == "") {
                Swal.fire(
                    'Error',
                    'Se debe de adjuntar una imagen',
                    'error'
                )
            }
        }
    </script>

    <script>
        tinymce.init({
            selector: '#descripcion',
            plugins: [
                'a11ychecker', 'advlist', 'advcode', 'advtable', 'autolink', 'checklist', 'export',
                'lists', 'link', 'image', 'charmap', 'preview', 'anchor', 'searchreplace', 'visualblocks',
                'powerpaste', 'fullscreen', 'formatpainter', 'insertdatetime', 'media', 'table', 'help', 'wordcount'
            ],
            toolbar: 'undo redo | formatpainter casechange blocks | bold italic backcolor | ' +
                'alignleft aligncenter alignright alignjustify | ' +
                'bullist numlist checklist outdent indent | removeformat | a11ycheck code table help'
        });
    </script>
}

NoticiasMVC/Views/Noticias/Edit.cshtml
@model NoticiasMVC.ViewModels.NoticiasView

@{
    ViewData["Title"] = "Editar Noticias";
}

<div class="row">
    <div class="col-12">
        <h4>@ViewData["Title"]</h4>
    </div>

    <form asp-action="Edit" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="Noticias.IdNoticia" hidden />
        <input asp-for="Noticias.ImagenNoticia" hidden />
        <input asp-for="Noticias.FechaIngreso" hidden />

        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-edit"></i> Actualización de Noticias
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-6 col-sm-12 mb-3">
                            <label class="form-label" asp-for="Noticias.TituloNoticia"></label>
                            <input asp-for="Noticias.TituloNoticia" class="form-control"
                                   placeholder="Ingresa el nombre de la categoria" />
                            <span class="text-danger" asp-validation-for="Noticias.TituloNoticia"></span>
                        </div>

                        <div class="col-lg-6 col-sm-12 mb-3">
                            <label class="form-label" asp-for="Noticias.ImagenNoticia"></label>
                            <input type="file" name="files" id="uploadBox" class="form-control" />
                        </div>

                        <div class="col-lg-6 col-sm-12 mb-3">
                            <label class="form-label" asp-for="Noticias.IdCategoria"></label>
                            <select asp-for="Noticias.IdCategoria" class="form-control" asp-items="@Model.CategoriasSelectList">
                                <option disabled selected>Seleccionar Categoría</option>
                            </select>
                            <span class="text-danger" asp-validation-for="Noticias.IdCategoria"></span>
                        </div>

                        <div class="col-lg-6 col-sm-12 mb-3">
                            <label class="form-label" asp-for="Noticias.IdClasificacion"></label>
                            <select asp-for="Noticias.IdClasificacion" class="form-control" asp-items="@Model.ClasificacionesSelectList">
                                <option disabled selected>Seleccionar Clasificación</option>
                            </select>
                            <span class="text-danger" asp-validation-for="Noticias.IdClasificacion"></span>
                        </div>

                        <div class="col-lg-6 col-sm-12">
                            <label class="form-label" asp-for="Noticias.DescripcionNoticia"></label>
                            <textarea asp-for="Noticias.DescripcionNoticia" class="form-control" id="descripcion" rows="5"></textarea>
                            <span class="text-danger" asp-validation-for="Noticias.DescripcionNoticia"></span>
                        </div>

                        <div class="col-lg-6 col-sm-12">
                            <label class="form-label">Imagen Actual</label>
                            <img src="@WebConst.NoticiasPath/@Model.Noticias.ImagenNoticia"
                                 style="width: 100%; border-radius: 5px; border: 1px solid #bbb" />
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-edit"></i> Actualizar
                    </button>

                    <a class="btn btn-danger" type="button" asp-action="Index">
                        <i class="fa fa-rotate-back"></i> Cancelar
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>
        tinymce.init({
            selector: '#descripcion',
            plugins: [
                'a11ychecker', 'advlist', 'advcode', 'advtable', 'autolink', 'checklist', 'export',
                'lists', 'link', 'image', 'charmap', 'preview', 'anchor', 'searchreplace', 'visualblocks',
                'powerpaste', 'fullscreen', 'formatpainter', 'insertdatetime', 'media', 'table', 'help', 'wordcount'
            ],
            toolbar: 'undo redo | formatpainter casechange blocks | bold italic backcolor | ' +
                'alignleft aligncenter alignright alignjustify | ' +
                'bullist numlist checklist outdent indent | removeformat | a11ycheck code table help'
        });
    </script>
}

NoticiasMVC/Views/Noticias/Index.cshtml
@model IEnumerable<NoticiasMVC.Models.Noticias>

@{
    ViewData["Title"] = "Lista de Noticias";
}

<div class="row">
    <div class="col-12 mt-3">
        <h4>
            @ViewData["Title"]
            <a class="btn btn-primary" asp-controller="Noticias" asp-action="Create">
                <i class="fa fa-pen"></i> Agregar
            </a>
        </h4>
    </div>

    <!--card Noticias-->
    <div class="col-12">
        <div class="card shadow-sm">
            <div class="card-header text-primary">
                <i class="fa-solid fa-database"></i> Lista de Registros
            </div>

            <div class="card-body">
                @if (Model.Count() > 0)
                {
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <tr>
                                <th>Id</th>
                                <th>Titular</th>
                                <th>Imagen</th>
                                <th>Categoría</th>
                                <th>Clasificación</th>
                                <th colspan="2">Opciones</th>
                            </tr>
                            @foreach (var Noticia in Model)
                            {
                                <tr>
                                    <td>@Noticia.IdNoticia</td>
                                    <td>@Noticia.TituloNoticia</td>
                                    <td>
                                        <img class="img-thumbnail" width="200px"
                                             src="@WebConst.NoticiasPath/@Noticia.ImagenNoticia">
                                    </td>
                                    <td>@Noticia.Categoria.NombreCategoria</td>
                                    <td>@Noticia.Clasificacion.NombreClasificacion</td>
                                    <td>
                                        <a class="btn btn-primary" asp-controller="Noticias"
                                   asp-action="Edit" asp-route-Id="@Noticia.IdNoticia">
                                            <i class="fa fa-edit"></i> Editar
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-danger" onclick="deleteNoticia(@Noticia.IdNoticia);">
                                            <i class="fa fa-trash"></i> Eliminar
                                        </a>
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                }
                else
                {
                    <div class="alert alert-primary">
                        No existen registros actuales de Noticias
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script>
        const deleteNoticia = (Id) => {
            Swal.fire({
                title: 'Quieres borrar esta Noticia?',
                text: "Una vez borrada no podras recurperarla",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si, eliminar!'
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire(
                        'Eliminado!',
                        'Tu registro fue eliminado correctamente.',
                        'success'
                    )
                    //espera para recargar la pagina
                    setTimeout(() => {
                        location.href = "/Noticias/Delete/" + Id
                    }, 500);
                }
            })
        }
    </script>
}